FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    chromium \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml .
COPY src/ src/

RUN pip install --no-cache-dir .
RUN mkdir /usr/local/lib/python3.12/site-packages/reporter/templates \
 && cp -r /app/src/reporter/templates/* /usr/local/lib/python3.12/site-packages/reporter/templates/

ENV CHROMIUM_PATH=/usr/bin/chromium

CMD ["python", "-m", "reporter"]
